set(CMAKE_AUTOUIC ON)
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG
    ${CMAKE_CURRENT_BINARY_DIR}/bin)
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_DEBUG
    ${CMAKE_CURRENT_BINARY_DIR}/bin)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_DEBUG
    ${CMAKE_CURRENT_BINARY_DIR}/bin)

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE
    ${CMAKE_CURRENT_BINARY_DIR}/bin)
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE
    ${CMAKE_CURRENT_BINARY_DIR}/bin)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE
    ${CMAKE_CURRENT_BINARY_DIR}/bin)

set(ACore_LIBS "acore")
set(ACore_Resource_DIR ${CMAKE_CURRENT_BINARY_DIR})
set(ACore_LIB_DIR ${CMAKE_CURRENT_BINARY_DIR}/bin)
set(ACore_BINARY_INCLUDE ${CMAKE_CURRENT_BINARY_DIR}/include)

if(CMAKE_BUILD_TYPE STREQUAL "Debug")
    set(IS_GENERAT_LIBRARY OFF)   # Debug 模式下启用调试
else()
    set(IS_GENERAT_LIBRARY ON)    # Release 模式关闭调试
endif()

