# base output
set(CMAKE_AUTOUIC ON)
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# DeBug output
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG
    ${CMAKE_CURRENT_BINARY_DIR}/bin)
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_DEBUG
    ${CMAKE_CURRENT_BINARY_DIR}/bin)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_DEBUG
    ${CMAKE_CURRENT_BINARY_DIR}/bin)

#release output
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE
    ${CMAKE_CURRENT_BINARY_DIR}/bin)
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE
    ${CMAKE_CURRENT_BINARY_DIR}/bin)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE
    ${CMAKE_CURRENT_BINARY_DIR}/bin)

# var set
set(ACore_Resource_DIR ${CMAKE_CURRENT_BINARY_DIR})
# set(CMAKE_INSTALL_PREFIX "${CMAKE_CURRENT_BINARY_DIR}/../../${PROJECT_NAME}") # 自己定义了库路径
set(ACore_SHARED_DIRS "${CMAKE_INSTALL_PREFIX}/bin")
SET(ACORE_STATIC_DIRS "${CMAKE_INSTALL_PREFIX}/lib")
set(ACore_INCLUDE_DIRS "${CMAKE_INSTALL_PREFIX}/include")

if(CMAKE_BUILD_TYPE STREQUAL "Debug")
    set(IS_GENERAT_LIBRARY OFF)   # Debug 模式下启用调试
else()
    set(IS_GENERAT_LIBRARY ON)    # Release 模式关闭调试
endif()

# set (CMAKE_C_COMPILER "C:/ProgramData/Qt6.8/Tools/mingw1310_64/bin/gcc.exe")
# set (CMAKE_CXX_COMPILER "C:/ProgramData/Qt6.8/Tools/mingw1310_64/bin/g++.exe")

set(IS_GENERAT_LIBRARY ON) # TODO 必要时候可以注释掉


