# 库设置
set(PROJECT_VERSION_MAJOR 1)
set(PROJECT_VERSION_MINOR 0)
set(PROJECT_VERSION_PATCH 0)
set(ACore_Version "${CMAKE_CURRENT_BINARY_DIR}/VersionInfo.rc")

set(ACORE_VER_FILEVERSION_QUAD "${PROJECT_VERSION_MAJOR},${PROJECT_VERSION_MINOR},${PROJECT_VERSION_PATCH},0")
set(ACORE_VER_PRODUCTVERSION_QUAD "${PROJECT_VERSION_MAJOR},${PROJECT_VERSION_MINOR},${PROJECT_VERSION_PATCH},0")
set(ACORE_VER_FILEVERSION_STR "${PROJECT_VERSION_MAJOR},${PROJECT_VERSION_MINOR},${PROJECT_VERSION_PATCH},0")
set(ACORE_VER_PRODUCTVERSION_STR "${PROJECT_VERSION_MAJOR},${PROJECT_VERSION_MINOR},${PROJECT_VERSION_PATCH},0")
set(ACORE_VER_COPYRIGHT_STR "HoeMuiiii")
set(ACORE_VER_PRODUCTNAME_STR "ACore")
set(ACORE_VER_HAVE_COPYRIGHT_STR 1)
set(ACORE_VER_HAVE_COMMENTS_STR 1)
