# base output
set(CMAKE_AUTOUIC ON)
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# DeBug output
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG
    ${CMAKE_CURRENT_BINARY_DIR}/bin)
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_DEBUG
    ${CMAKE_CURRENT_BINARY_DIR}/bin)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_DEBUG
    ${CMAKE_CURRENT_BINARY_DIR}/bin)

#release output
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE
    ${CMAKE_CURRENT_BINARY_DIR}/bin)
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE
    ${CMAKE_CURRENT_BINARY_DIR}/bin)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE
    ${CMAKE_CURRENT_BINARY_DIR}/bin)

if(CMAKE_BUILD_TYPE STREQUAL "Debug")
    set(IS_GENERAT_LIBRARY OFF)   # Debug 模式下启用调试
else()
    set(IS_GENERAT_LIBRARY ON)    # Release 模式关闭调试
endif()

# include(./CMakePackageConfigHelpers)# TODO 需要自动定位 ACore_DIRS 时放开注释

# TODO 手动设置位置
set(IS_GENERAT_LIBRARY ON) # 是否生成库/或者是调试模式
set(CMAKE_INSTALL_PREFIX "${CMAKE_CURRENT_BINARY_DIR}/../${PROJECT_NAME}") # 自定义安装位置
set(ACore_LIBS "${CMAKE_INSTALL_PREFIX}/lib/lib${PROJECT_NAME}.dll.a")     # 静态库位置（安装后）
set(ACore_Resource_DIR ${CMAKE_CURRENT_BINARY_DIR})
set(ACore_SHARED_DIRS "${CMAKE_INSTALL_PREFIX}/bin")                       # 动态库位置（安装后）
SET(ACORE_STATIC_DIRS "${CMAKE_INSTALL_PREFIX}/lib")                       # 静态库位置（安装后）
set(ACore_INCLUDE_DIRS "${CMAKE_INSTALL_PREFIX}/include")                  # 头文件位置（安装后）
set(ACore_INCLUDE_DIRS_CONFIGCMAKE "${CMAKE_CURRENT_BINARY_DIR}/include")  # 未定义


